-- MySQL Script generated by MySQL Workbench
-- Mon May 11 17:57:35 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema litoralalertabd
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `litoralalertabd` ;

-- -----------------------------------------------------
-- Schema litoralalertabd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `litoralalertabd` DEFAULT CHARACTER SET utf8mb3 ;
USE `litoralalertabd` ;

-- -----------------------------------------------------
-- Table `litoralalertabd`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `litoralalertabd`.`usuario` ;

CREATE TABLE IF NOT EXISTS `litoralalertabd`.`usuario` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `nome` VARCHAR(50) NULL DEFAULT NULL,
  `foto_perfil` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `senha` VARCHAR(80) NULL DEFAULT NULL,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  `bio` VARCHAR(255) NULL DEFAULT NULL,
  `local` VARCHAR(50) NULL DEFAULT NULL,
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `litoralalertabd`.`publicacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `litoralalertabd`.`publicacao` ;

CREATE TABLE IF NOT EXISTS `litoralalertabd`.`publicacao` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `resumo` VARCHAR(255) NULL DEFAULT NULL,
  `slug` VARCHAR(255) NULL DEFAULT NULL,
  `conteudo` TEXT NULL DEFAULT NULL,
  `foto_capa` VARCHAR(255) NULL DEFAULT NULL,
  `acessos` INT NOT NULL DEFAULT '0',
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  `data_publicacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuario_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_noticia_usuario_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_noticia_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `litoralalertabd`.`usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `litoralalertabd`.`comentario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `litoralalertabd`.`comentario` ;

CREATE TABLE IF NOT EXISTS `litoralalertabd`.`comentario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `conteudo` TEXT NOT NULL,
  `data` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuario_id` INT UNSIGNED NOT NULL,
  `publicacao_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comentario_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_comentario_publicacao1_idx` (`publicacao_id` ASC) VISIBLE,
  CONSTRAINT `fk_comentario_publicacao1`
    FOREIGN KEY (`publicacao_id`)
    REFERENCES `litoralalertabd`.`publicacao` (`id`),
  CONSTRAINT `fk_comentario_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `litoralalertabd`.`usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `litoralalertabd`.`curtir`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `litoralalertabd`.`curtir` ;

CREATE TABLE IF NOT EXISTS `litoralalertabd`.`curtir` (
  `publicacao_id` INT UNSIGNED NOT NULL,
  `usuario_id` INT UNSIGNED NOT NULL,
  `data` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`publicacao_id`, `usuario_id`),
  INDEX `fk_publicacao_has_usuario_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_publicacao_has_usuario_publicacao1_idx` (`publicacao_id` ASC) VISIBLE,
  CONSTRAINT `fk_publicacao_has_usuario_publicacao1`
    FOREIGN KEY (`publicacao_id`)
    REFERENCES `litoralalertabd`.`publicacao` (`id`),
  CONSTRAINT `fk_publicacao_has_usuario_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `litoralalertabd`.`usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `litoralalertabd`.`seguir`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `litoralalertabd`.`seguir` ;

CREATE TABLE IF NOT EXISTS `litoralalertabd`.`seguir` (
  `seguidor_id` INT UNSIGNED NOT NULL,
  `seguido_id` INT UNSIGNED NOT NULL,
  `data` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`seguidor_id`, `seguido_id`),
  INDEX `fk_usuario_has_usuario_usuario2_idx` (`seguido_id` ASC) VISIBLE,
  INDEX `fk_usuario_has_usuario_usuario1_idx` (`seguidor_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_usuario_usuario1`
    FOREIGN KEY (`seguidor_id`)
    REFERENCES `litoralalertabd`.`usuario` (`id`),
  CONSTRAINT `fk_usuario_has_usuario_usuario2`
    FOREIGN KEY (`seguido_id`)
    REFERENCES `litoralalertabd`.`usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
